on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Setup Python
       uses: actions/setup-python@v3.1.2
       with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'
     - name: Install Dependencies
       run: |
        pip install discord-webhook
        pip install get-chrome-driver --upgrade
        pip install -r selenium/requirements.txt
     - name: Run Python
       env: 
        DISCORD_KIRINUKI_WEBHOOK_URL: ${{ secrets.DISCORD_KIRINUKI_WEBHOOK_URL }}
        YOUTUBE_URL: ${{ secrets.YOUTUBE_URL }}
       run: python webhook.py
