on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Setup Python
       uses: actions/setup-python@v3.1.2
       with:
        python-version: '3.8'
        architecture: 'x64'
     - name: Install Dependencies
       run: pip install discord-webhook
     - name: Run Python
       env: 
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
       run: python webhook.py
